name: Ruff Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff-format:
  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      run: git checkout -f
    - name: Set up Python
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install --upgrade virtualenv
        virtualenv -p python3.8 venv
        . venv/bin/activate
    - name: Install dependencies
      run: |
        pip install ruff
    - name: Format code
      run: |
        ruff format
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -m "Ruff format"
