name: ruff format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '>=3.8'
    - run: |
        python -m pip install --upgrade pip
        pip install ruff
    - run: ruff format --check .